// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent until the first build
import { default as nextHandler } from "./.open-next/worker.js";

// Keys must match `triggers.crons` in wrangler.jsonc character for character. Cron Triggers run
// in UTC. MON-FRI rather than 1-5 because cron dialects disagree on whether 1 is Sunday or Monday.
export const CRON_ROUTES: Record<string, string> = {
  "0 4 * * MON-FRI": "/api/cron/reminder", // 09:30 IST
  "30 4 * * MON-FRI": "/api/cron/summary", // 10:00 IST
};

export default {
  fetch: nextHandler.fetch,

  async scheduled(controller, env, ctx) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.error("no route for cron", { cron: controller.cron });
      return;
    }
    const request = new Request(`https://standup-bot.internal${path}`, {
      method: "POST",
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response: Response = await nextHandler.fetch(request, env, ctx);
    const body = await response.text();
    if (!response.ok) {
      console.error("cron job failed", { cron: controller.cron, path, status: response.status, body });
      return;
    }
    console.log("cron job done", { cron: controller.cron, path, body });
  },
} satisfies ExportedHandler<CloudflareEnv>;
